[project]
authors = ["wingerted <wingerted@gmail.com>"]
channels = ["conda-forge"]
description = "Conda package for libassert"
name = "libassert"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = "*"
ninja = "*"
clang = "*"
clangxx = "*"
rattler-build = "*"
ccache = "*"
