package:
  name: libassert
  version: 2.1.4_2

source:
  git: https://github.com/jeremy-rifkin/libassert.git
  tag: v2.1.4

build:
  script: ./build.sh

requirements:
  build:
    - clang
    - clangxx
    - cmake
    - ninja
  host:
    - zlib
  run: []  # 运行时依赖自动从 host 继承

# 包的元数据
about:
  homepage: https://github.com/jeremy-rifkin/libassert
  license: MIT
  summary: A modern assertion library for C++
