name: Release Conda Package

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的 tag 时触发

# 添加权限配置
permissions:
  contents: write  # 允许工作流创建 releases

jobs:
  build-and-release:
    name: Build and Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pixi
        shell: bash
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pixi install

      - name: Build conda package
        run: |
          pixi run rattler-build build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/**/*.conda
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 